<style>
    body {
        margin: 0 !important;
    }
    #jsm-drwl {
        background-color: rgba(0, 32, 64, .96);
        border-radius: 12px 0 0 12px;
        box-shadow: 0 0 12px rgba(0, 16, 32, .96);
        color: white;
        cursor: pointer;
        display: block;
        font-family: "Lucida Console", Monaco, monospace;
        font-size: 10pt;
        height: 12px;
        line-height: 1;
        padding: 10px 14px 10px 8px;
        position: fixed;
        left: calc(100% - 34px);
        top: 17px;
        transition: .125s;
        user-select: none;
        white-space: nowrap;
    }
    #jsm-drwl:hover {
        text-shadow: 0 0 6px white;
    }
    #jsm-drwl.active {
        left: auto;
        right: 0;
    }
    #jsm-drwl .all-green {
        color: yellowgreen;
    }
    #jsm-drwl .warning {
        color: tomato;
    }
    #jsm-console {
        background-color: rgba(0, 32, 64, .96);
        border-radius: 12px 0 0 0;
        box-shadow: 0 0 12px rgba(0, 16, 32, .96);
        color: white;
        font-family: "Lucida Console", Monaco, monospace;
        font-size: 10pt;
        height: calc(100% - 90px);
        overflow-y: scroll;
        padding: 10px;
        position: fixed;
        right: -440px;
        text-shadow: 0 0 6px rgba(0, 32, 64, .96);
        top: 70px;
        transition: .125s;
        width: 420px;
    }
    #jsm-console.active {
        right: -15px;
    }
    #jsm-console .toggle-button {
        background-color: rgba(0, 32, 64, .96);
        border-radius: 12px 0 0 12px;
        box-shadow: 0 0 12px rgba(0, 16, 32, .96);
        cursor: pointer;
        display: block;
        font-size: 24px;
        height: 32px;
        padding-right: 2px;
        position: fixed;
        right: 0;
        text-align: center;
        top: 75px;
        transition: .125s;
        user-select: none;
        width: 32px;
    }
    #jsm-console.active .toggle-button {
        background-color: transparent;
        border-radius: 0;
        box-shadow: none;
        top: 73px;
        transform: rotate(-45deg);
        -webkit-transform: rotate(-45deg);
    }
    #jsm-console .toggle-button:hover {
        text-shadow: 0 0 6px white;
    }
</style>

<span id="jsm-drwl" class="active">
    DR (WL): <strong></strong>
</span>

<div id="jsm-console">
    <span class="toggle-button">&oplus;</span>
    <strong>User defined costants</strong>:
    <p>
        <?php
        foreach ($cons['user'] as $key => $value) {
            if (is_null($value)) {
                $value = 'NULL';
            } else if (is_bool($value)) {
                $value = $value ? 'TRUE' : 'FALSE';
            } else if (is_string($value)) {
                $value = '"' . $value .'"';
            }
            echo $key . ': <strong>' . $value . '</strong><br />';
        }
        ?>
    </p>
    <br />
    <br />
</div>

<script>
    $(function()
    {
        var jsmDrwl = $('#jsm-drwl'),
            jsmDrwlStrong = jsmDrwl.children('strong'),
            jsmDrwlStrongMs = Date.now() - startTime,
            jsmConsole = $('#jsm-console'),
            jsmConsoleToggleButton = jsmConsole.children('.toggle-button'),
            jsm;

        jsmDrwlStrong.text(jsmDrwlStrongMs + "ms").addClass(jsmDrwlStrongMs > 1000 ? 'warning' : 'all-green');

        $(window).on('load', function(e)
        {
            var jsmDrwlStrongText = jsmDrwlStrong.text();

            jsmDrwlStrong.text(jsmDrwlStrongText + ' (' + (Date.now() - startTime) + 'ms)');
        });

        jsmDrwl.on('click', function (e)
        {
            $(this).toggleClass('active');//fadeOut(125);
        });

        jsmConsoleToggleButton.on('click', function(e)
        {
            jsmConsole.toggleClass('active');
        });
    });
</script>
