<?php

/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com and you will be sent a copy immediately.
 *
 * PHP version 7.2.18
 *
 * @category Frontend\Console
 * @package  JSM
 * @author   Bertozzi Matteo <bertozzi@i-ways.net>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License 3.0
 * @link     https://github.com/TheB3Rt0z
 */
?>

<style>
    body {
        margin: 0 !important;
    }
    .right-bar {
        background-color: rgba(0, 32, 64, .96);
        border-radius: 12px 0 0 0;
        box-shadow: 0 0 6px rgba(0, 16, 32, .96);
        color: white;
        font-family: "Lucida Console", Monaco, monospace;
        font-size: 10pt;
        position: fixed;
        text-shadow: 0 0 6px rgba(0, 32, 64, .96);
        transition: .125s;
    }
    .right-bar .toggle-button {
        cursor: pointer;
        font-size: 24px;
        left: 6px;
        position: absolute;
        top: 4px;
        transition: .125s;
        user-select: none;
    }
    #jsm-console.right-bar .toggle-button {
        background-color: rgba(0, 32, 64, .96);
        border-radius: 12px 0 0 12px;
        box-shadow: 0 0 6px rgba(0, 16, 32, .96);
        display: block;
        height: 32px;
        left: auto;
        position: fixed;
        right: 0;
        text-align: center;
        top: 68px;
        width: 32px;
    }
    .right-bar.active .toggle-button {
        transform: rotate(-45deg);
        -webkit-transform: rotate(-45deg);
    }
    #jsm-console.right-bar.active .toggle-button {
        background-color: transparent;
        border-radius: 0;
        box-shadow: none;
        top: 66px;
    }
    .right-bar .toggle-button:hover {
        text-shadow: 0 0 6px white;
    }
    #jsm-drwl {
        border-radius: 12px 0 0 12px;
        display: block;
        height: 12px;
        line-height: 1;
        padding: 10px 8px 10px 32px;
        left: calc(100% - 32px);
        top: 17px;
        white-space: nowrap;
    }
    #jsm-drwl.active {
        left: auto;
        right: 0;
    }
    #jsm-drwl .all-green {
        color: yellowgreen;
    }
    #jsm-drwl .warning {
        color: tomato;
    }
    #jsm-console {
        height: calc(100% - 83px);
        overflow-y: scroll;
        padding: 10px;
        right: -440px;
        top: 63px;
        width: 420px;
    }
    #jsm-console.active {
        right: -15px;
    }
</style>

<span id="jsm-drwl" class="right-bar active">
    <span class="toggle-button">&oplus;</span>
    document ready in
    <strong></strong>
</span>

<div id="jsm-console" class="right-bar">
    <span class="toggle-button">&oplus;</span>
    <strong>User defined costants</strong>:
    <p>
        <?php
        foreach ($cons['user'] as $key => $value) {
            if (is_null($value)) {
                $value = 'NULL';
            } else if (is_bool($value)) {
                $value = $value ? 'TRUE' : 'FALSE';
            } else if (is_string($value)) {
                $value = '"' . $value .'"';
            }
            echo $key . ': <strong>' . $value . '</strong><br />';
        }
        ?>
    </p>
    <br />
    <br />
</div>

<script>
    $(function()
    {
        var jsmDrwl = $('#jsm-drwl'),
            jsmDrwlStrong = jsmDrwl.children('strong'),
            jsmDrwlStrongMs = Date.now() - startTime,
            jsmRightBarToggleButtons = $('.right-bar .toggle-button');

        jsmDrwlStrong.text(jsmDrwlStrongMs + "ms")
                     .addClass(jsmDrwlStrongMs > 1000 ? 'warning' : 'all-green');

        jsmRightBarToggleButtons.on('click', function(e)
        {
            $(this).parent().toggleClass('active');
        });
    });
</script>
